apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  APP_ENV: production
  FEATURE_ANALYTICS: "true"
  WELCOME_MESSAGE: Hello from Kubernetes ConfigMap
  WORKER_SERVICE_URL: http://worker-service:8001
  REDIS_HOST: redis-service
  REDIS_PORT: "6379"
  WORKER_NAME: cluster-worker

